# https://taskfile.dev

version: '3'

vars:
  VULKAN_SDK: "/Users/ogmalladii/VulkanSDK/1.3.261.1"
  GLFW_INCLUDE_DIR: "/opt/homebrew/opt/glfw/include"
  ZIGC: "/Users/ogmalladii/dev/zig/installations/zig-macos-aarch64-0.12.0-dev.1808+69195d0cd/zig"

tasks:
  compile-shaders:
    dir: "{{.ROOT_DIR}}/shaders"
    vars:
      OUTPUT_DIR: "compiled_output"
      GLSLC: "{{.VULKAN_SDK}}/macOS/bin/glslc"
    sources:
      - "*.vert"
      - "*.frag"
    cmds:
      - for: sources
        cmd: "{{.GLSLC}} {{.ITEM}} -o {{.OUTPUT_DIR}}/{{.ITEM}}.spv"

  build:
    vars:
      OPTIMIZATION: '{{default "Debug" .OPTIMIZATION}}'
    cmds:
      - task: compile-shaders
      - "{{.ZIGC}} build -Doptimize={{.OPTIMIZATION}}" 
    env:
      VK_ICD_FILENAMES: "{{.VULKAN_SDK}}/macOS/share/vulkan/icd.d/MoltenVK_icd.json"
      VK_LAYER_PATH: "{{.VULKAN_SDK}}/macOS/share/vulkan/explicit_layer.d"

  build-release-fast:
    cmds:
      - task: build 
        vars: { OPTIMIZATION: "ReleaseFast" }

  run:
    cmds:
      - "zig-out/bin/game_engine"
    env:
      DYLD_LIBRARY_PATH: "{{.VULKAN_SDK}}/macOS/lib:/opt/homebrew/opt/glfw/lib:/opt/homebrew/opt/glm/lib:/Users/ogmalladii/dev/zig/game_engine/external/cglm-0.9.1/build"
        
  test-file:
    cmds:
      - task: build
      - "{{.ZIGC}} test {{.CLI_ARGS}}"

  debug:
    cmds:
      - "lldb zig-out/bin/game_engine"
    env:
      DYLD_LIBRARY_PATH: "{{.VULKAN_SDK}}/macOS/lib:/opt/homebrew/opt/glfw/lib:/opt/homebrew/opt/glm/lib:/Users/ogmalladii/dev/zig/game_engine/external/cglm-0.9.1/build"

  cimgui-generate:
    dir: "{{.ROOT_DIR}}/external/cimgui/generator"
    cmds:
      - "./generator.sh"
    env:
      VULKAN_SDK: "{{.VULKAN_SDK}}/macOS/include"
      VK_ICD_FILENAMES: "{{.VULKAN_SDK}}/macOS/share/vulkan/icd.d/MoltenVK_icd.json"
      VK_LAYER_PATH: "{{.VULKAN_SDK}}/macOS/share/vulkan/explicit_layer.d"
      GLFW_INCLUDE_DIR: "{{.GLFW_INCLUDE_DIR}}"

