# https://taskfile.dev

version: '3'

vars:
  VULKAN_SDK: "/Users/ogmalladii/VulkanSDK/1.3.261.1"

tasks:
  compile-shaders:
    dir: "{{.ROOT_DIR}}/shaders"
    vars:
      OUTPUT_DIR: "compiled_output"
      GLSLC: "{{.VULKAN_SDK}}/macOS/bin/glslc"
    sources:
      - "*.vert"
      - "*.frag"
    cmds:
      - for: sources
        cmd: "{{.GLSLC}} {{.ITEM}} -o {{.OUTPUT_DIR}}/{{.ITEM}}.spv"

  build:
    vars:
      OPTIMIZATION: '{{default "Debug" .OPTIMIZATION}}'
    cmds:
      - task: compile-shaders
      - "zig build -Doptimize={{.OPTIMIZATION}}" 
    env:
      VK_ICD_FILENAMES: "{{.VULKAN_SDK}}/macOS/share/vulkan/icd.d/MoltenVK_icd.json"
      VK_LAYER_PATH: "{{.VULKAN_SDK}}/macOS/share/vulkan/explicit_layer.d"

  build-release-fast:
    cmds:
      - task: build 
        vars: { OPTIMIZATION: "ReleaseFast" }

  run:
    cmds:
      - "zig-out/bin/game_engine"
    env:
      DYLD_LIBRARY_PATH: "/Users/ogmalladii/VulkanSDK/1.3.261.1/macOS/lib:/opt/homebrew/opt/glfw/lib:/opt/homebrew/opt/glm/lib:/Users/ogmalladii/dev/zig/game_engine/external/cglm-0.9.1/build"
